### DISCUSSION TITLE
Bug or feature: consult-line does not search

### DISCUSSION THREAD

**Discussion by jsirex** [minad/consult#1216] [Q&A] [answered]
I made little file

```toml
[foo-banner]
banner-strategy = "ridiculous-banner"
banner-system = "foo"
```

Mode does not matter, actually.
1. `M-x consult-line` (all 3 lines displayed in preview)
2. Start typing `banner`. After `b` only 2 condidates left. The line `[foo-banner]` is not available anymore

So for me it is similar to "search does not work". 
When I start search with ` b` (space + b) all 3 lines match.

My completion styles `completion-styles '(partial-completion orderless)`, but I'm not sure does it matter.
Is it bug or feature? Looks like, if my search matches directly beginning of a line, everything other removed.
